### PR TITLE
fix: Deprecation of the setMetadataCacheImpl method

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by alcaeus** [comment]
There's a little more work to be done here, as the signatures of the methods are not compatible. If you're interested in working on this, check the corresponding PR for the DoctrineBundle: https://github.com/doctrine/DoctrineBundle/pull/1332.

**Comment by soyuka** [comment]
I see it got merged, feel free to close this if not required anymore.

**Comment by alcaeus** [comment]
This was done in ODM itself, but needs more work here. Let me know if you want to make the changes, otherwise I'll take care of that later this week.

**Comment by alcaeus** [comment]
Closing in favour of #675.

**Pull request closed without merging**
