### PR TITLE
Bump coding standard to v11

### PR DESCRIPTION
**Pull request by franmomu**
Use the latest `doctrine/coding-standard` version ([it supports `"php": "^7.2 || ^8.0"`](https://github.com/doctrine/coding-standard/blob/eec72ad87d3d5d2e8f2aefb58b3880f019b88a7e/composer.json#L25))

### CODE REVIEW

**Comment by IonBazan** [comment]
@franmomu please rebase - there is a conflict after I merged #755

**Comment by franmomu** [comment]
I have to check why it fails 😕

**Comment by franmomu** [comment]
I guess it's because in:

https://github.com/symfony/symfony/blob/2f62c4a7951ed05e722638beb3dcdea7c650a3a2/src/Symfony/Bridge/Doctrine/DependencyInjection/AbstractDoctrineExtension.php#L320-L326

it doesn't match with `/** @Document **/`, I guess there should be a way to not modify these annotation for now.

**Comment by IonBazan** [comment]
Ouch, yes. I think you can add all test fixtures to ignore the coding standard or at least that particular rule.

**Review by IonBazan — APPROVED** [review]
LGTM 👍🏻

**Comment by IonBazan** [comment]
Thanks @franmomu!

**Pull request merged**
