### PR TITLE
Add tests to the build matrix

### PR DESCRIPTION
**Pull request by theofidry**
* Add tests against all Symfony LTS versions
* Add tests against PHP7 & HHVM (are allowed to failed for now)
* Enable fast finish

### CODE REVIEW

**Comment by theofidry** [comment]
Tests are failing on Symfony 3.0 :(

**Comment by alcaeus** [comment]
Thanks for your PR. Since there is no ext-mongo for PHP 7 and HHVM and ODM does not yet support the new ext-mongodb driver there is no point in adding PHP 7 or HHVM to the build matrix.

Support for Symfony 3.0 will be added in an upcoming release. That branch will have one of the last 2.x LTS versions as a minimum requirement and we'll be dropping ll older releases (including the 2.3 LTS release).

Last but not least, keeping up with the other Doctrine MongoDB packages we'll also drop support for PHP < 5.5 and ext-mongo < 1.5.

**Comment by theofidry** [comment]
Any date for the support of Symfony 3.0?

**Comment by alcaeus** [comment]
When it's done - don't know any more than that at this time.

**Pull request closed without merging**
