### PR TITLE
Removing travis allow failure for php7.4

### PR DESCRIPTION
**Pull request by ishyevandro**
#587

### CODE REVIEW

**Comment by alcaeus** [comment]
@ishyevandro thanks for the contribution. Could you please rebase the PR and point it to the 3.6 branch? Thanks!

**Comment by ishyevandro** [comment]
Hi @alcaeus, i don't get it.

Can you explain with more details? (New in the world of contribution)

**Comment by alcaeus** [comment]
As I was writing up the guideline I noticed that we don't test 3.6 against PHP 7.4 at all. So there are no changes necessary from your end here. Instead, I suggest we take care of this in a separate pull request. If you're up for it, go ahead and give it a shot!

**Comment by ishyevandro** [comment]
@alcaeus, i there's one fail in 7.3 and deprecation problems in all versions.
How could i proceed?
https://github.com/doctrine/DoctrineMongoDBBundle/pull/589

https://travis-ci.org/doctrine/DoctrineMongoDBBundle/builds/591927014

**Comment by alcaeus** [comment]
#586 will fix these deprecations, we'll take another look afterwards 👍

**Comment by alcaeus** [comment]
Thanks @ishyevandro!

**Pull request merged**
