### PR TITLE
sanity-check DI configuration

### PR DESCRIPTION
**Pull request by dbu**
redoing #184 as i already deleted my fork and thus can't update the PR anymore.

moved validation into Configuration instead of the extension class.

### CODE REVIEW

**Comment by jmikola** [comment]
@dbu: Does this resolve all of the outstanding TODO items (or make them irrelevant) from #184?

**Comment by dbu** [comment]
it does not adress the feature request to split configuration between connection configuration and document manager: https://github.com/doctrine/DoctrineMongoDBBundle/pull/184/files#r3856315

but i think everything else is covered, yes.

**Comment by dbu** [comment]
@jmikola this one is old. still want to merge it maybe?

**Comment by alcaeus** [comment]
@dbu Sorry for the long delay, can you rebase this once again?

**Comment by dbu** [comment]
just did the rebase. hope it still ends up green.

**Comment by alcaeus** [comment]
Thanks!

**Comment by dbu** [comment]
you are welcome!

**Pull request merged**
