### PR TITLE
replaced app/console with bin/console

### PR DESCRIPTION
**Pull request by roman-1983**

### CODE REVIEW

**Comment by malarzm** [comment]
@roman-1983 just for an update: I'm procrastinating with clicking the green button only to have two versions of documentation, for 2.x and 3.x versions of Symfony. The PR will be merged soon :)

**Comment by roman-1983** [comment]
thanks for your feedback. ;)

**Comment by malarzm** [comment]
To cross reference: https://github.com/symfony/symfony-docs/issues/6516

**Comment by malarzm** [comment]
Probably we won't see documentation on Symfony updated anytime soon so I'll just merge this and hope folks using old Symfony folder layout will know where their `console` is...

**Pull request merged**
