### PR TITLE
[WIP] Autowiring for repository classes

### PR DESCRIPTION
**Pull request by michaelperrin**
This is the state of my work to implement autowiring for repository (#443).
Most of the work is a port of Ryan Weaver's contribution to the ORM (https://github.com/doctrine/DoctrineBundle/pull/727).

The implementation should be ok, but I haven't tested it yet and the unit tests are not done at all (they are still copied and pasted from @weaverryan work 😖).

I will try to work on it as soon as possible. Feel free to contribute too, or to start the work all over again!

### CODE REVIEW

**Comment by weaverryan** [comment]
+1! Will be great to have consistency and bring this feature to the ODM. AFAIK, there haven’t been any big issues for the ORM - so the idea is now fairly well battle tested.

**Comment by michaelperrin** [comment]
I may have some time by the end of the week to work on it again :) I keep you posted.

**Comment by Pavel1986** [comment]
👎

**Comment by alcaeus** [comment]
@Pavel1986 would you like to add something constructive or how am I supposed to understand your comment?

**Comment by michaelperrin** [comment]
@alcaeus I preferred to ignore it 😄

And by the way, don't think that I don't work at all on the feature. I am still working on it at times (no later than last Friday for example), but nothing appears as I squash my commits.

**Comment by alcaeus** [comment]
@michaelperrin no worries - we all have busy lives, which unfortunately means less time for Open Source projects. Anybody who needs this badly can gladly offer their help. Thanks for the work you've done and are doing on this!

**Comment by alcaeus** [comment]
@michaelperrin did you manage to finish something for service repositories in the meantime? If so, could you push your WIP code so I can continue it? I'd like to include these in the next release and would finish the feature myself if you don't have the time 👍

**Comment by alcaeus** [comment]
Closing in favour of #473.

**Comment by michaelperrin** [comment]
@alcaeus I am so sorry I could not manage it (and didn't see your last comment), and thank you very much for your work!
I do hope I will help in some other way soon (I finally get a bit of time)!

**Comment by alcaeus** [comment]
No worries 🍻

**Pull request closed without merging**
