### PR TITLE
Add missing service for command GenerateRepositoriesDoctrineODMCommand

### PR DESCRIPTION
**Pull request by enekochan**
As above :)

### CODE REVIEW

**Comment by malarzm** [comment]
Seems like a bug to me ;)

**Comment by enekochan** [comment]
When is intended to be released the 3.4.4 tag? This bug prevents from upgrading to Symfony 4.0 ATM

**Comment by alcaeus** [comment]
I can take care of it later today unless @malarzm gets there first.

**Comment by alcaeus** [comment]
3.4.4 has been released: https://github.com/doctrine/DoctrineMongoDBBundle/releases/tag/3.4.4

**Pull request merged**
