### PR TITLE
fix documentation links

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by malarzm** [comment]
Thank you @xabbuh and sorry for long merge time!

**Comment by xabbuh** [comment]
@malarzm You're welome. I'll check if everything renders as expected on symfony.com after the next build of the documentation.

**Comment by malarzm** [comment]
@xabbuh out of curiosity - how often do the builds run?

**Comment by xabbuh** [comment]
@malarzm Once at about 5am CET IIRC.

**Comment by malarzm** [comment]
Thanks!

**Comment by malarzm** [comment]
@xabbuh if I'm seeing correctly only two links are off: `using common Doctrine extensions`_ and `the cookbook`_ - will you submit a PR for that or shall I?

**Comment by xabbuh** [comment]
@malarzm Sure, I'll do that tonight.

**Comment by malarzm** [comment]
Thanks in advance! :)

**Pull request merged**
