### PR TITLE
Symfony 3 support

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Cherry-picked @tomasbro commit from #310 for form deprecations.

Code deprecation globally reviewed and corrected.

Please tell me if something is missing.

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
Fixed some missing stuff. Travis is green, should be OK now. :+1:

**Comment by theofidry** [comment]
:+1:

**Comment by alcaeus** [comment]
Thank you! I'll take a look at this over the weekend and do some more to get Symfony 3.0 support going.

**Comment by Soullivaneuh** [comment]
> and do some more to get Symfony 3.0 support going.

What is missing?

**Comment by alcaeus** [comment]
Along with the next version that will support Symfony 3 we are removing support for older PHP and ext-mongo versions.

**Comment by Soullivaneuh** [comment]
I would suggest to put a new patch or minor version with this PR to add SF 3.0 support as this version is already stable.

Then, PHP and extensions support dropping could be worked after. :+1:

**Comment by alcaeus** [comment]
Superseded by #328, thank you for your help. Please continue all discussion in the new PR.

**Pull request closed without merging**
