### PR TITLE
Drop support of PHP < 7.4

### PR DESCRIPTION
**Pull request by franmomu**
As we did it [in the ODM](https://github.com/doctrine/mongodb-odm/pull/2466) I think we can do the same for the `4.6.0` release.

### CODE REVIEW

**Review by SenseException — APPROVED** [review]
I suppose PHP 7 will be completely dropped in 5.0.x.

**Comment by franmomu** [comment]
Looking at the installs https://packagist.org/packages/doctrine/mongodb-odm-bundle/php-stats#4.5, 20% are still using 7.4, so I think we should keep it for now.

**Review by IonBazan — APPROVED** [review]
Are there any specific PHP 7.4 features we can use in this bundle after this PR is merged?

**Comment by franmomu** [comment]
> Are there any specific PHP 7.4 features we can use in this bundle after this PR is merged?

Yeah, we can add types to private properties, I'll do it in another PR.

**Pull request merged**
