### PR TITLE
Changed toolbar design to 2.8+ style

### PR DESCRIPTION
**Pull request by snagels**
This pull request will make the profiler debug toolbar extension more accurate to current symfony design

### CODE REVIEW

**Comment by malarzm** [comment]
@snagels thanks for the PR! Could we leave both classes as we still support 2.7 or does it break things?

**Comment by snagels** [comment]
@malarzm This would break the design again, but there is a workaround. There is a variable you can ask for the version. I will implement this and update the pull request.

**Comment by malarzm** [comment]
Great, thanks a bunch @snagels!

**Comment by stof** [comment]
This is no enough to support the new profiler design fully. Icons should use SVG now (see DoctrineBundle for instance)

**Comment by malarzm** [comment]
@snagels would you mind taking care of icons @stof is pointing out?

**Comment by snagels** [comment]
@malarzm I will take care of it as soon as possible.

**Comment by malarzm** [comment]
:+1:

**Pull request merged**
